### ISSUE TITLE
Changing Gamma and Gaussian broadening in XAS calculations has no effect

### ISSUE THREAD

**Issue by kkummer** [mretegan/crispy#75]
Changing the Gamma parameter to adjust the life time broadening in XAS calculations and the Gaussian resolution broadening does not have an effect. When starting a calculation they seem to be set back to the default values and calculations run with different Gamma and Gaussian parameters all yield the same spectra.

**Comment by mretegan** [comment]
@kkummer In version 0.7.3, every time one of those values is changed, you need to press return to submit; otherwise, it is not considered. In the development version, this remains the same, but the user has a visual indication (the background becomes yellow) that the value was changed. When the user presses return, the value is submitted, and the background is changed to white.

https://user-images.githubusercontent.com/93124/193801016-16456186-8016-4d62-ab6c-3dcd3bd67fda.mov
